### PR TITLE
Changes for moodle 4/php 8, error corrections

### LINKED ISSUE #24: renderer.php
Hi,
I've noticed an issue concerning Moodle 3.11.3+ (Build: 20211019).  In the "general settings" menu there are the following debugging messages:
-Notice: Undefined variable: cleanupusers in /var/www/html/admin/tool/cleanupusers/renderer.php on line 62

-Warning: array_key_exists() expects parameter 2 to be array, null given in /var/www/html/admin/tool/cleanupusers/renderer.php on line 276

Thank you!

Alex

### PR DESCRIPTION
**Pull request by my-curiosity**
Hello,

This PR solves some issues I found while testing the plugin on moodle 4 + php 8 and fixes #24:

- `renderer.php` uses an unidentified variable `$cleanupusers`, already mentioned in #24. This leads to an `array_key_exists()` call with `null` as a parameter (which is an error in php 8)
- Some old fields of `mdl_user` table are not present in 4.0: for example, you can compare https://www.examulator.com/er/3.7/output/tables/user.html with https://www.examulator.com/er/4.0/tables/user.html (moodle 4.1 also adds a `firstlogin` field, but this PR ignores it). If I understand correctly, `tool_cleanupusers_archive` table mimics `mdl_user` schema, so the fields should also be removed
- `$cloneuser->imagealt` is set twice in `archiveduser.php`
- Plugin requires moodle 3.1+ but uses features from at least 3.9 (such as `moodlenetprofile` field)

Fixes:
- Remove `$cleanupusers` form `renderer.php`, check if users are archived from db instead(as in `information_user_reactivate()`)
- Remove `'icq'`, `'skype'`, `'yahoo'`, `'aim'`, `'msn'` and `'url'` fields from the archive table by changing `install.xml` and `upgrade.php`
- Change second `$cloneuser->imagealt` to `$cloneuser->moodlenetprofile`, remove old fields from `archiveduser.php`
- Correct some errors in comments
- Require moodle 4.0+ (optional)

### CODE REVIEW

**Comment by NinaHerrmann** [comment]
Hey @my-curiosity ,
Thank you so much for the pull request. As our university might switch to another user management system, we are not really working on the tool anymore... 
The pull request looks pretty good from my point of view, I was just wondering if you could give me a reminder of how the variable $cleanupuser was used at all ... 
Otherwise, I am happy to merge the Pull Request! Thank you so much!

**Comment by my-curiosity** [comment]
It looks like `$cleanupusers` was added in https://github.com/learnweb/moodle-tool_cleanupusers/pull/21/commits/55e087bc6dd45726fa1a7e7bcdb2a67ac5f21c94#diff-e82e7ce1e17af09c0cd0f5fee5930434efabb50487fa59a889bc3ba36503c1b8 and was meant to store an array of all currently archived users, probably to optimize repeating db calls in `information_user_...()` functions. However, the definition in line 48 was removed here: https://github.com/learnweb/moodle-tool_cleanupusers/pull/21/commits/8272401c7a8dd29208a2ad48c41a11c1ce0d2aba#diff-e82e7ce1e17af09c0cd0f5fee5930434efabb50487fa59a889bc3ba36503c1b8 so the variable remained undefined. 

I have now updated the PR to redefine it instead of removing completely (and also use it for `information_user_reactivate()`, no idea why it was not).

**Comment by NinaHerrmann** [comment]
I hope this is okay, I just added the GitHub actions so I do not have to run tests on my machine.
In an ideal world, we would deal with the 3_11 to 4_00 change until December with some if statements...
But I understand, and agree that most likely not so many people are using the plugin so don't feel pressured to change it.

Regarding the code checker, I had some time at the airport so I thought I clean it up... :joy:

**Comment by NinaHerrmann** [comment]
Ah one more thing... 
did you tested the usage of `get_all_user_name_fields()` because it is supposed to be deprecated so it might lead to some problems? 
https://tracker.moodle.org/browse/MDL-45242

**Comment by my-curiosity** [comment]
More tests is always a good idea, so GHA should be useful.
Regarding `get_all_user_name_fields()`, I did not systematically check for deprecation/warnings, only tried to hotfix (possibly) breaking changes, bugs and some comment errors. It should be possible to replace it with `\core_user\fields::get_name_fields()`, though.

**Comment by NinaHerrmann** [comment]
If it is just the replacement I would be really glad if you can shortly do that! ☺️

**Comment by my-curiosity** [comment]
Sure, I will try to fix unit tests and change it after.

**Comment by my-curiosity** [comment]
`get_all_user_name_fields()` is replaced with new fields API. Unit tests are a bit chaotic, but should also work now after small changes. I have also left some comments in `tests/generator/lib.php` to clarify what happens with each test user during cron test (to my understanding). If something is wrong, feel free to make corrections.

**Comment by NinaHerrmann** [comment]
To be honest, I will not check the test cases. I scanned them, and do not have the time to look at all of them. Please only use the tool with a reasonable amount of checking! There is a reason why we list the tool as `MATURITY_ALPHA`.

Beside that, thank you for your work and fast answers!

**Comment by my-curiosity** [comment]
Of course, this seems reasonable.

And thank you for merging the PR.

**Pull request merged**
